services:
  - type: web
    name: screenplay-api
    env: docker
    region: oregon  # or change to your preferred region
    plan: free      # or 'starter', 'standard', etc.
    dockerfilePath: ./Dockerfile
    buildCommand: ""  # optional, Render uses Dockerfile instructions
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /
    autoDeploy: true
